[package]
name = "exonum-configuration"
version = "0.2.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/configuration-updater/"
repository = "https://github.com/exonum/exonum-configuration"
documentation = "https://docs.rs/exonum-configuration"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "config", "configuration"]
categories = ["database-implementations", "config"]
description = "An Exonum service that provides functionality of modifying the global configuration."

[badges]
travis-ci = { repository = "exonum/exonum-configuration" }

[dependencies]
exonum = { version = "0.2", git = "https://github.com/aleksuss/exonum", branch = "rocksdb-fork-cf" }
clap = "2.14"
tempdir = "0.3.5"
env_logger = "0.3"
log = "0.3.0"
serde = "1.0.0"
serde_derive = "1.0.0"
lazy_static = "0.2.8"
router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.7.0"
params = "0.6.0"
