[package]
name = "exonum-configuration"
version = "0.3.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/configuration-updater/"
repository = "https://github.com/exonum/exonum-configuration"
documentation = "https://docs.rs/exonum-configuration"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "config", "configuration"]
categories = ["database-implementations", "config"]
description = "An Exonum service that provides functionality of modifying the global configuration."

[badges]
travis-ci = { repository = "exonum/exonum-configuration" }

[dependencies]
exonum = "0.3.0"
clap = "2.25.0"
tempdir = "0.3.5"
env_logger = "0.4.3"
log = "0.3.8"
serde = "1.0.10"
serde_derive = "1.0.10"
lazy_static = "0.2.9"
router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.7.0"
params = "0.6.0"

[dev-dependencies]
pretty_assertions = "0.4.0"

[dev-dependencies.exonum-testkit]
git = "https://github.com/exonum/exonum-testkit"
rev = "8a5371d00141475bb07458f0d08e605102005d18"

[patch.crates-io]
exonum = { git = "https://github.com/exonum/exonum", rev = "3ffaf6c7f2bf93e42cb70b10a8a0d02077691fe2" }
